
SLASH_INVITE1 = "/i"; -- Invite
SLASH_INVITE2 = "/inv"; -- Invite
SLASH_INVITE3 = "/invite"; -- Invite
SLASH_UNINVITE1 = "/u"; -- Uninvite
SLASH_UNINVITE2 = "/un"; -- Uninvite
SLASH_UNINVITE3 = "/kick"; -- Uninvite
SLASH_UNINVITE4 = "/uninvite"; -- Uninvite
SLASH_RANDOM1 = "/rnd";
SLASH_RANDOM2 = "/random";
SLASH_RANDOM3 = "/rand";

SLASH_PARTY1 = "/p"; -- Party
SLASH_PARTY3 = "/p"; -- Party
SLASH_PARTY2 = "/party"; -- Party
SLASH_SAY1 = "/s"; -- Say
SLASH_SAY2 = "/say"; -- Say
SLASH_SAY3 = "/s"; -- Say
SLASH_YELL1 = "/y"; -- Yell
SLASH_YELL4 = "/shout"; -- Yell
SLASH_YELL3 = "/sh"; -- Yell
SLASH_YELL2 = "/yell"; -- Yell
SLASH_GUILD1 = "/g"; -- Guild
SLASH_GUILD2 = "/gc"; -- Guild
SLASH_GUILD3 = "/gu"; -- Guild
SLASH_GUILD4 = "/guild"; -- Guild
SLASH_WHISPER1 = "/w"; -- Whisper
SLASH_WHISPER2 = "/whisper"; -- Whisper
SLASH_WHISPER3 = "/t"; -- Whisper
SLASH_WHISPER4 = "/tell"; -- Whisper
SLASH_WHISPER5 = "/send"; -- Whisper