
SLASH_INVITE1 = "/i"; -- Invite
SLASH_INVITE2 = "/inv"; -- Invite
SLASH_INVITE3 = "/invite"; -- Invite
SLASH_UNINVITE1 = "/u"; -- Uninvite
SLASH_UNINVITE2 = "/un"; -- Uninvite
SLASH_UNINVITE3 = "/kick"; -- Uninvite
SLASH_UNINVITE4 = "/uninvite"; -- Uninvite
SLASH_RANDOM1 = "/rnd";
SLASH_RANDOM2 = "/random";
SLASH_RANDOM3 = "/rand";

SLASH_PARTY1 = "/p"; -- Party
SLASH_PARTY3 = "/p"; -- Party
SLASH_PARTY2 = "/party"; -- Party
SLASH_SAY1 = "/s"; -- Say
SLASH_SAY2 = "/say"; -- Say
SLASH_SAY3 = "/s"; -- Say
SLASH_YELL1 = "/y"; -- Yell
SLASH_YELL4 = "/shout"; -- Yell
SLASH_YELL3 = "/sh"; -- Yell
SLASH_YELL2 = "/yell"; -- Yell
SLASH_GUILD1 = "/g"; -- Guild
SLASH_GUILD2 = "/gc"; -- Guild
SLASH_GUILD3 = "/gu"; -- Guild
SLASH_GUILD4 = "/guild"; -- Guild
SLASH_WHISPER1 = "/w"; -- Whisper
SLASH_WHISPER2 = "/whisper"; -- Whisper
SLASH_WHISPER3 = "/t"; -- Whisper
SLASH_WHISPER4 = "/tell"; -- Whisper
SLASH_WHISPER5 = "/send"; -- Whisper
SLASH_GUILD_INVITE1 = "/ginvite"; -- Guild invite
SLASH_GUILD_INVITE2 = "/guildinvite"; -- Guild invite
SLASH_GUILD_LEADER1 = "/gleader"; -- Guild leader
SLASH_GUILD_LEADER2 = "/guildleader"; -- Guild leader
SLASH_GUILD_LEAVE1 = "/gquit"; -- Guild leave
SLASH_GUILD_LEAVE2 = "/guildquit"; -- Guild leave
SLASH_GUILD_MOTD1 = "/gmotd"; -- Guild MOTD
SLASH_GUILD_MOTD2 = "/guildmotd"; -- Guild MOTD
SLASH_GUILD_DEMOTE1 = "/gdemote"; -- Guild demote
SLASH_GUILD_DEMOTE2 = "/guilddemote"; -- Guild demote
SLASH_GUILD_PROMOTE1 = "/gpromote"; -- Guild promote
SLASH_GUILD_PROMOTE2 = "/guildpromote"; -- Guild promote
SLASH_GUILD_UNINVITE1 = "/gremove"; -- Guild uninvite
SLASH_GUILD_UNINVITE2 = "/guildremove"; -- Guild uninvite
SLASH_GUILD_DISBAND1 = "/gdisband"; -- Guild disband
SLASH_GUILD_DISBAND2 = "/guilddisband"; -- Guild disband
SLASH_LOGOUT1 = "/logout"; -- Logout
SLASH_LOGOUT2 = "/camp"; -- Logout
SLASH_QUIT1 = "/quit"; -- Quit
SLASH_QUIT2 = "/exit"; -- Quit
SLASH_TIME1 = "/time"; -- Time
SLASH_PLAYED1 = "/played"; -- Played time
SLASH_PLAYED2 = "/playtime"; -- Played time
SLASH_FRIENDINVITE1 = "/friendinvite"; -- Friend invite
SLASH_FRIENDINVITE2 = "/finvite"; -- Friend invite
SLASH_FRIENDINVITE3 = "/fi"; -- Friend invite
SLASH_FRIENDREMOVE1 = "/friendremove"; -- Friend remove
SLASH_FRIENDREMOVE2 = "/fremove"; -- Friend remove
SLASH_FRIENDREMOVE3 = "/fr"; -- Friend remove
SLASH_FRIENDLIST1 = "/friendlist"; -- Friend list
SLASH_FRIENDLIST2 = "/friends"; -- Friend list